name: Delta Blues Event Design
favicon: null
layout_spectrum: 0.50994
typography_spectrum: 0.76763
title: Delta Blues Event Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#339db1'
    - '#7bf9ea'
    - '#2e656c'
    - '#f0fefc'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.42600852088071406
  rhythmicContrast: 0.25
purpose: []
